### ISSUE TITLE
arubaoscx.patch and arubaoss.patch can not be found on GIT

### ISSUE THREAD

**Issue by kermitsweetwater** [aruba/aruba-switch-ansible#1]
Attempting to download the patches arubaoscx.patch and arubaoss.patch, but they can't be found. Also a search of all GitHub provides no results... Where can these patches be found? Thanks, Jim I'm interested in using the modules that would be found in ansible/modules/network/arubaoss

**Comment by Oswaldbob** [comment]
Patch files can be found in this Directory:
https://github.com/aruba/aruba-switch-ansible/tree/master/module_integration

**Comment by kermitsweetwater** [comment]
thank!

**Comment by rajani-abraham** [comment]
You can see the wiki on how to install these here 
https://github.com/aruba/aruba-switch-ansible/wiki/Module-Integration

**Comment by kermitsweetwater** [comment]
Was able to successfully apply the arubaoscx.patch but when attempting to apply the arubaoss.patch 
receive the following errors. 

/usr/lib/python2.7/dist-packages$ sudo git apply /home/jim/my-project.git/aruba-switch-ansible/module_integration/arubaoss.patch
error: patch failed: ansible/config/base.yml:1413
error: ansible/config/base.yml: patch does not apply
error: ansible/module_utils/network/arubaoss/__init__.py: already exists in working directory
error: ansible/module_utils/network/arubaoss/arubaoss.py: already exists in working directory
error: ansible/modules/network/arubaoss/__init__.py: already exists in working directory
error: ansible/modules/network/arubaoss/arubaoss_aaa_accounting.py: already exists in working directory
error: ansible/modules/network/arubaoss/arubaoss_aaa_authentication.py: already exists in working directory
error: ansible/modules/network/arubaoss/arubaoss_aaa_authorization.py: already exists in working directory
error: ansible/modules/network/arubaoss/arubaoss_acl_policy.py: already exists in working directory
error: ansible/modules/network/arubaoss/arubaoss_captive_portal.py: already exists in working directory
error: ansible/modules/network/arubaoss/arubaoss_config_bkup.py: already exists in working directory
error: ansible/modules/network/arubaoss/arubaoss_dns.py: already exists in working directory
error: ansible/modules/network/arubaoss/arubaoss_dot1x.py: already exists in working directory
error: ansible/modules/network/arubaoss/arubaoss_file_transfer.py: already exists in working directory
error: ansible/modules/network/arubaoss/arubaoss_interface.py: already exists in working directory
error: ansible/modules/network/arubaoss/arubaoss_ip_auth.py: already exists in working directory
error: ansible/modules/network/arubaoss/arubaoss_ip_route.py: already exists in working directory
error: ansible/modules/network/arubaoss/arubaoss_loop_protect.py: already exists in working directory
error: ansible/modules/network/arubaoss/arubaoss_macAuthentication.py: already exists in working directory
error: ansible/modules/network/arubaoss/arubaoss_ntp.py: already exists in working directory
error: ansible/modules/network/arubaoss/arubaoss_poe.py: already exists in working directory
error: ansible/modules/network/arubaoss/arubaoss_port_rate_limit.py: already exists in working directory
error: ansible/modules/network/arubaoss/arubaoss_qos_policy.py: already exists in working directory
error: ansible/modules/network/arubaoss/arubaoss_radius_profile.py: already exists in working directory
error: ansible/modules/network/arubaoss/arubaoss_reboot.py: already exists in working directory
error: ansible/modules/network/arubaoss/arubaoss_routing.py: already exists in working directory
error: ansible/modules/network/arubaoss/arubaoss_snmp.py: already exists in working directory
error: ansible/modules/network/arubaoss/arubaoss_snmp_trap.py: already exists in working directory
error: ansible/modules/network/arubaoss/arubaoss_stp.py: already exists in working directory
error: ansible/modules/network/arubaoss/arubaoss_syslog.py: already exists in working directory
error: ansible/modules/network/arubaoss/arubaoss_system_attributes.py: already exists in working directory
error: ansible/modules/network/arubaoss/arubaoss_tacas_profile.py: already exists in working directory
error: ansible/modules/network/arubaoss/arubaoss_traffic_class.py: already exists in working directory
error: ansible/modules/network/arubaoss/arubaoss_user.py: already exists in working directory
error: ansible/modules/network/arubaoss/arubaoss_vlan.py: already exists in working directory
error: ansible/plugins/action/arubaoss.py: already exists in working directory

**Comment by kermitsweetwater** [comment]
was installed thanks
