### ISSUE TITLE
 Banner motd #

### ISSUE THREAD

**Issue by kermitsweetwater** [aruba/aruba-switch-ansible#2]
Do you have an example yml that shows how configure a banner on the switch using the 'banner motd #' command?
Thank you

**Comment by kermitsweetwater** [comment]
resolved

**Comment by Sethueha** [comment]
Could you please provide the resolution steps. I want to do a banner configuration in HP Procurve switches using aruba_config module.

**Comment by cyrmoon** [comment]
HOW ?

**Comment by sstrijak** [comment]
Try do the following:

    - name: Generate config
      set_fact:
        cfglines:
          - 'session interactive-mode disable'
          - 'banner motd "!!!!!!!!!!!!!!!!!!!!!WARNING! FINAL NOTICE!!!!!!!!!!!!!!!!!!!!!!!!\nOnly authorised users may access this system."'
          - 'session interactive-mode enable'

    - name: Push configuration
      community.network.aruba_config:
        commands: "{{ cfglines }}"
        match: none
        save_when: always
      register: cfgresult
