### ISSUE TITLE
Fix alternative command - for applying patches

### ISSUE THREAD

**Issue by Pack3tL0ss** [aruba/aruba-switch-ansible#4]
The command noted as (Alternative if above does not work) in the modules_integration wiki page...
`"patch -p1 path_to_patch_file/filename.patch"`

Should be 
`patch -p1 --verbose < path_to_patch_file/filename.patch"`

The verbose is optional, but the redirecting the file contents is necessary otherwise the patch command will just hang (waiting for input from stdin).  I believe there is are (-i | --input) options for "patch", but as printed it doesn't do anything.

UPDATE: better yet just update the readme, and point them to the aruba-ansible-modules repo for install instructions

**Comment by hrv231** [comment]
I'm having the same issue, running now ansible 2.8 devel version on CentOS 7, everything goes fine with the command for arubaoscx but not for arubaoss.

```
[root@netbox site-packages]# patch -p1 --verbose < /etc/ansible/aruba-switch-ansible/module_integration/arubaoss.patch 
Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|diff --git a/ansible/config/base.yml b/ansible/config/base.yml
|index 1929d81..8031e92 100644
|--- a/ansible/config/base.yml
|+++ b/ansible/config/base.yml
--------------------------
patching file ansible/config/base.yml
Using Plan A...
Hunk #1 FAILED at 1413.
1 out of 1 hunk FAILED -- saving rejects to file ansible/config/base.yml.rej
```

I had to manually add the line into the NETWORK_GROUP_MODULES , hopefully that will fix it for now.
Still I have to test the module and playbooks, but this is an issue.

**Comment by rajani-abraham** [comment]
Thanks for trying. Please use https://github.com/aruba/aruba-ansible-modules to install ansible modules for now. We will be fixing wiki to point to that github instructions for Ansible module installation.
