### ISSUE TITLE
many references to files, in ansible integration wiki don't match any filenames in repo

### ISSUE THREAD

**Issue by Pack3tL0ss** [aruba/aruba-switch-ansible#5]
many references to files, in ansible integration wiki don't match any filenames in repo

aoscx.yml
aoss.yml

"Adding switch project integration" also includes reference to prem.sh which doesn't exist in repo.

Additionally:  Typo under the heading: Setup Module Examples for Ansible Tower
The description line just under the headings for aoss.yml and aoscx.yml are reversed.... 
i.e. "This will change the hostname of the AOS-Switch device (Host: switch1_switch)." is under the aoscx.yml heading.

**Comment by rajani-abraham** [comment]
We are working on the wiki of this repo to make it easier. Stay tuned.

**Comment by tchiapuziowong** [comment]
Fixed these issues in the latest commit https://github.com/aruba/aruba-switch-ansible/commit/c11e330f70949fb9191a35df6eec44e12f84ca68
