### ISSUE TITLE
API doesn't report back changes

### ISSUE THREAD

**Issue by cirola2000** [aruba/aruba-switch-ansible#8]
Hi there,

Every time a request is made, the response returned has the "changed" filed always set to false:

``` ... 
        "changed": false, 
        "connection": "close", 
        "content_type": "application/json", 
        "cookies": {}, 
...
 ```

This behavior makes nearly impossible to detect whether a change was made or not, and the roles end up always being wrongly idempotent. 

I'm using firmware v. WC_16_07_0005.

**Comment by tchiapuziowong** [comment]
What module are you experiencing this with? Can you provide the task you're using in the playbook?

**Comment by cirola2000** [comment]
Sure,

changing the DNS:
``` 
- name: Configure DNS for ArubaOS Switch
  uri:
    url: "http://{{ hostvars[inventory_hostname].ansible_host }}/rest/v4/dns"
    method: PUT
    headers:
       Cookie: '{{ switch_session.json.cookie }}'
    body_format: json
    body: {"dns_config_mode": "DCM_MANUAL", "server_1": {"version":"IAV_IP_V4", "octets": "8.8.8.8" }, "dns_domain_names": ["dnsname.com"] }
    validate_certs: no
    status_code: 200
  register: result
- debug: var=result 
```

The same happens trying to set the hostname:
```
- name: Aruba AOS-S Change Hostname
  uri:
    url: "http://{{ hostvars[inventory_hostname].ansible_host  }}/rest/v4/system"
    method: PUT
    headers:
      cookie: '{{ switch_session.json.cookie }}'
    body: {"name": "dasdsai"}
    body_format: json
    validate_certs: no
    status_code: 200
  register: system_data
- debug: var=system_data
```

Notice that the changes **are applied**, therefore the "changed" response is always false.

**Comment by tchiapuziowong** [comment]
Those modules are using Ansible's URI module to send raw REST commands. For the modules we've created that include idempotency checks I would recommend cloning this repo and installing our modules: https://github.com/aruba/aruba-ansible-modules

There you should be able to get the results you're looking for! I'm currently working on drastically updating this repo, in the update I'll be modifying the Wiki and the workflows as well as update documentation to point to our updated Aruba Switching Modules repo. Apologies for any confusion this might have caused!

**Comment by cirola2000** [comment]
Awesome,

Thank you very much, @tchiapuziowong.
